-- 코드를 입력하세요
SELECT B.AUTHOR_ID, B.AUTHOR_NAME, A.CATEGORY, SUM(A.PRICE * C.SALES) TOTAL_SALES
FROM  BOOK A
JOIN AUTHOR B 
ON A.AUTHOR_ID = B.AUTHOR_ID
JOIN BOOK_SALES C 
ON C.BOOK_ID = A.BOOK_ID
WHERE DATE_FORMAT(SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY B.AUTHOR_ID , B.AUTHOR_NAME, A.CATEGORY
ORDER BY B.AUTHOR_ID,  A.CATEGORY DESC